services:
 - docker
language: cpp
before_install:
  - docker pull grumpycoders/uc-sdk-build-env
env:
  matrix:
    - TARGET=inemom1/leds
    - TARGET=stm32f4discovery/skel
    - TARGET=stm32f429discovery/leds
    - TARGET=mbed-lpc1768/leds
script:
  - docker run -v `pwd`:/uC-sdk grumpycoders/uc-sdk-build-env make -C /uC-sdk/examples/$TARGET
notifications:
  email: false
